# Generated by Django 2.2.5 on 2019-09-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='use',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='bonus',
            name='use',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='easy',
            name='use',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='hard_for_men',
            name='use',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='hard_for_women',
            name='use',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='medium',
            name='use',
            field=models.BooleanField(null=True),
        ),
    ]
