# Generated by Django 2.2.5 on 2019-10-01 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gaming', '0002_auto_20190930_1140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hard_for_men',
            new_name='HardForMen',
        ),
        migrations.RenameModel(
            old_name='Hard_for_women',
            new_name='HardForWomen',
        ),
    ]
